<style type="text/css">
    select {
      font-family: 'FontAwesome', 'sans-serif';
    }
</style>
<div class="form-group {{ $errors->has('title') ? 'has-error' : ''}}">
    <label for="title" class="col-md-4 control-label">{{ 'Title' }}</label>
    <div class="col-md-6">
        <input class="form-control" name="title" type="text" id="title" value="{{ $propertytype->title??''}}" required>
        {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('property_type') ? 'has-error' : ''}}">
    <label for="status" class="col-md-4 control-label">{{ 'For' }}</label>
    <div class="col-md-6">
        <select class="form-control" id="icon" name="property_type">
            <option value="buy" @if(isset($propertytype->property_type) && $propertytype->property_type == 'buy' )  selected @endif >Buy</option>
            <option value="sale" @if(isset($propertytype->property_type) && $propertytype->property_type == 'sale' )  selected @endif>Sale</option>
        </select>
        {!! $errors->first('property_type', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('description') ? 'has-error' : ''}}">
    <label for="description" class="col-md-4 control-label">{{ 'Description' }}</label>
    <div class="col-md-6">
        <textarea class="form-control" rows="5" name="description" type="textarea" id="description" >{{ $propertytype->description??''}}</textarea>
        {!! $errors->first('description', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('icon') ? 'has-error' : ''}}">
    <label for="icon" class="col-md-4 control-label">{{ 'Icon' }}</label>
    <div class="col-md-6">
        <select class="form-control" id="icon" name="icon">
            <option value="fa fa-align-left  icon icon-size">&#xf036; fa-align-left</option>
            <option value="fa fa-align-right icon icon-size">&#xf038; fa-align-right</option>
            <option value="fa fa-amazon icon icon-size">&#xf270; fa-amazon</option>
            <option value="fa fa-ambulance icon icon-size">&#xf0f9; fa-ambulance</option>
            <option value="fa fa-anchor icon icon-size">&#xf13d; fa-anchor</option>
            <option value="fa fa-android icon icon-size">&#xf17b; fa-android</option>
            <option value="fa fa-angellist icon icon-size">&#xf209; fa-angellist</option>
            <option value="fa fa-angle-double-down icon icon-size">&#xf103; fa-angle-double-down</option>
            <option value="fa fa-angle-double-left icon icon-size">&#xf100; fa-angle-double-left</option>
            <option value="fa fa-angle-double-right icon icon-size">&#xf101; fa-angle-double-right</option>
            <option value="fa fa-angle-double-up icon icon-size">&#xf102; fa-angle-double-up</option>
            <option value="fa fa-angle-left icon icon-size">&#xf104; fa-angle-left</option>
            <option value="fa fa-angle-right icon icon-size">&#xf105; fa-angle-right</option>
            <option value="fa fa-angle-up icon icon-size">&#xf106; fa-angle-up</option>
            <option value="fa fa-apple icon icon-size">&#xf179; fa-apple</option>
            <option value="fa fa-archive icon icon-size">&#xf187; fa-archive</option>
            <option value="fa fa-area-chart icon icon-size">&#xf1fe; fa-area-chart</option>
            <option value="fa fa-arrow-circle-down icon icon-size">&#xf0ab; fa-arrow-circle-down</option>
            <option value="fa fa-arrow-circle-left icon icon-size">&#xf0a8; fa-arrow-circle-left</option>
            <option value="fa fa-arrow-circle-o-down icon icon-size">&#xf01a; fa-arrow-circle-o-down</option>
            <option value="fa fa-arrow-circle-o-left icon icon-size">&#xf190; fa-arrow-circle-o-left</option>
            <option value="fa fa-arrow-circle-o-right icon icon-size">&#xf18e; fa-arrow-circle-o-right</option>
            <option value="fa fa-arrow-circle-o-up icon icon-size">&#xf01b; fa-arrow-circle-o-up</option>
            <option value="fa fa-arrow-circle-right icon icon-size">&#xf0a9; fa-arrow-circle-right</option>
            <option value="fa fa-arrow-circle-up icon icon-size">&#xf0aa; fa-arrow-circle-up</option>
            <option value="fa fa-arrow-down icon icon-size">&#xf063; fa-arrow-down</option>
            <option value="fa fa-arrow-left icon icon-size">&#xf060; fa-arrow-left</option>
            <option value="fa fa-arrow-right icon icon-size">&#xf061; fa-arrow-right</option>
            <option value="fa fa-arrow-up icon icon-size">&#xf062; fa-arrow-up</option>
            <option value="fa fa-arrows icon icon-size">&#xf047; fa-arrows</option>
            <option value="fa fa-arrows-alt icon icon-size">&#xf0b2; fa-arrows-alt</option>
            <option value="fa fa-arrows-h icon icon-size">&#xf07e; fa-arrows-h</option>
            <option value="fa fa-arrows-v icon icon-size">&#xf07d; fa-arrows-v</option>
            <option value="fa fa-asterisk icon icon-size">&#xf069; fa-asterisk</option>
            <option value="fa fa-at icon icon-size">&#xf1fa; fa-at</option>
            <option value="fa fa-automobile icon icon-size">&#xf1b9; fa-automobile</option>
            <option value="fa fa-backward icon icon-size">&#xf04a; fa-backward</option>
            <option value="fa fa-balance-scale icon icon-size">&#xf24e; fa-balance-scale</option>
            <option value="fa fa-ban icon icon-size">&#xf05e; fa-ban</option>
            <option value="fa fa-bank icon icon-size">&#xf19c; fa-bank</option>
            <option value="fa fa-bar-chart icon icon-size">&#xf080; fa-bar-chart</option>
            <option value="fa fa-bar-chart-o icon icon-size">&#xf080; fa-bar-chart-o</option>
            <option value="fa fa-battery-full icon icon-size">&#xf240; fa-battery-full</option>
            n value="fa fa-beer icon icon-size">&#xf0fc; fa-beer</option>
            <option value="fa fa-behance icon icon-size">&#xf1b4; fa-behance</option>
            <option value="fa fa-behance-square icon icon-size">&#xf1b5; fa-behance-square</option>
            <option value="fa fa-bell icon icon-size">&#xf0f3; fa-bell</option>
            <option value="fa fa-bell-o icon icon-size">&#xf0a2; fa-bell-o</option>
            <option value="fa fa-bell-slash icon icon-size">&#xf1f6; fa-bell-slash</option>
            <option value="fa fa-bell-slash-o icon icon-size">&#xf1f7; fa-bell-slash-o</option>
            <option value="fa fa-bicycle icon icon-size">&#xf206; fa-bicycle</option>
            <option value="fa fa-binoculars icon icon-size">&#xf1e5; fa-binoculars</option>
            <option value="fa fa-birthday-cake icon icon-size">&#xf1fd; fa-birthday-cake</option>
            <option value="fa fa-bitbucket icon icon-size">&#xf171; fa-bitbucket</option>
            <option value="fa fa-bitbucket-square icon icon-size">&#xf172; fa-bitbucket-square</option>
            <option value="fa fa-bitcoin icon icon-size">&#xf15a; fa-bitcoin</option>
            <option value="fa fa-black-tie icon icon-size">&#xf27e; fa-black-tie</option>
            <option value="fa fa-bold icon icon-size">&#xf032; fa-bold</option>
            <option value="fa fa-bolt icon icon-size">&#xf0e7; fa-bolt</option>
            <option value="fa fa-bomb icon icon-size">&#xf1e2; fa-bomb</option>
            <option value="fa fa-book icon icon-size">&#xf02d; fa-book</option>
            <option value="fa fa-bookmark icon icon-size">&#xf02e; fa-bookmark</option>
            <option value="fa fa-bookmark-o icon icon-size">&#xf097; fa-bookmark-o</option>
            <option value="fa fa-briefcase icon icon-size">&#xf0b1; fa-briefcase</option>
            <option value="fa fa-btc icon icon-size">&#xf15a; fa-btc</option>
            <option value="fa fa-bug icon icon-size">&#xf188; fa-bug</option>
            <option value="fa fa-building icon icon-size">&#xf1ad; fa-building</option>
            <option value="fa fa-building-o icon icon-size">&#xf0f7; fa-building-o</option>
            <option value="fa fa-bullhorn icon icon-size">&#xf0a1; fa-bullhorn</option>
            <option value="fa fa-bullseye icon icon-size">&#xf140; fa-bullseye</option>
            <option value="fa fa-bus icon icon-size">&#xf207; fa-bus</option>
            <option value="fa fa-cab icon icon-size">&#xf1ba; fa-cab</option>
            <option value="fa fa-calendar icon icon-size">&#xf073; fa-calendar</option>
            <option value="fa fa-camera icon icon-size">&#xf030; fa-camera</option>
            <option value="fa fa-car icon icon-size">&#xf1b9; fa-car</option>
            <option value="fa fa-caret-up icon icon-size">&#xf0d8; fa-caret-up</option>
            <option value="fa fa-cart-plus icon icon-size">&#xf217; fa-cart-plus</option>
            <option value="fa fa-cc icon icon-size">&#xf20a; fa-cc</option>
            <option value="fa fa-cc-amex icon icon-size">&#xf1f3; fa-cc-amex</option>
            <option value="fa fa-cc-jcb icon icon-size">&#xf24b; fa-cc-jcb</option>
            <option value="fa fa-cc-paypal icon icon-size">&#xf1f4; fa-cc-paypal</option>
            <option value="fa fa-cc-stripe icon icon-size">&#xf1f5; fa-cc-stripe</option>
            <option value="fa fa-cc-visa icon icon-size">&#xf1f0; fa-cc-visa</option>
            <option value="fa fa-chain icon icon-size">&#xf0c1; fa-chain</option>
            <option value="fa fa-check icon icon-size">&#xf00c; fa-check</option>
            <option value="fa fa-chevron-left icon icon-size">&#xf053; fa-chevron-left</option>
            <option value="fa fa-chevron-right icon icon-size">&#xf054; fa-chevron-right</option>
            <option value="fa fa-chevron-up icon icon-size">&#xf077; fa-chevron-up</option>
            <option value="fa fa-child icon icon-size">&#xf1ae; fa-child</option>
            <option value="fa fa-chrome icon icon-size">&#xf268; fa-chrome</option>
            <option value="fa fa-circle icon icon-size">&#xf111; fa-circle</option>
            <option value="fa fa-circle-o icon icon-size">&#xf10c; fa-circle-o</option>
            <option value="fa fa-circle-o-notch icon icon-size">&#xf1ce; fa-circle-o-notch</option>
            <option value="fa fa-circle-thin icon icon-size">&#xf1db; fa-circle-thin</option>
            <option value="fa fa-clipboard icon icon-size">&#xf0ea; fa-clipboard</option>
            <option value="fa fa-clock-o icon icon-size">&#xf017; fa-clock-o</option>
            <option value="fa fa-clone icon icon-size">&#xf24d; fa-clone</option>
            <option value="fa fa-close icon icon-size">&#xf00d; fa-close</option>
            <option value="fa fa-cloud icon icon-size">&#xf0c2; fa-cloud</option>
            <option value="fa fa-cloud-download icon icon-size">&#xf0ed; fa-cloud-download</option>
            <option value="fa fa-cloud-upload icon icon-size">&#xf0ee; fa-cloud-upload</option>
            <option value="fa fa-cny icon icon-size">&#xf157; fa-cny</option>
            <option value="fa fa-code icon icon-size">&#xf121; fa-code</option>
            <option value="fa fa-code-fork icon icon-size">&#xf126; fa-code-fork</option>
            <option value="fa fa-codepen icon icon-size">&#xf1cb; fa-codepen</option>
            <option value="fa fa-coffee icon icon-size">&#xf0f4; fa-coffee</option>
            <option value="fa fa-cog icon icon-size">&#xf013; fa-cog</option>
            <option value="fa fa-cogs icon icon-size">&#xf085; fa-cogs</option>
            <option value="fa fa-columns icon icon-size">&#xf0db; fa-columns</option>
            <option value="fa fa-comment icon icon-size">&#xf075; fa-comment</option>
            <option value="fa fa-comment-o icon icon-size">&#xf0e5; fa-comment-o</option>
            <option value="fa fa-commenting icon icon-size">&#xf27a; fa-commenting</option>
            <option value="fa fa-commenting-o icon icon-size">&#xf27b; fa-commenting-o</option>
            <option value="fa fa-comments icon icon-size">&#xf086; fa-comments</option>
            <option value="fa fa-comments-o icon icon-size">&#xf0e6; fa-comments-o</option>
            <option value="fa fa-compass icon icon-size">&#xf14e; fa-compass</option>
            <option value="fa fa-compress icon icon-size">&#xf066; fa-compress</option>
            <option value="fa fa-connectdevelop icon icon-size">&#xf20e; fa-connectdevelop</option>
            <option value="fa fa-contao icon icon-size">&#xf26d; fa-contao</option>
            <option value="fa fa-copy icon icon-size">&#xf0c5; fa-copy</option>
            <option value="fa fa-copyright icon icon-size">&#xf1f9; fa-copyright</option>
            <option value="fa fa-creative-commons icon icon-size">&#xf25e; fa-creative-commons</option>
            <option value="fa fa-credit-card icon icon-size">&#xf09d; fa-credit-card</option>
            <option value="fa fa-crop icon icon-size">&#xf125; fa-crop</option>
            <option value="fa fa-crosshairs icon icon-size">&#xf05b; fa-crosshairs</option>
            <option value="fa fa-css3 icon icon-size">&#xf13c; fa-css3</option>
            <option value="fa fa-cube icon icon-size">&#xf1b2; fa-cube</option>
            <option value="fa fa-cubes icon icon-size">&#xf1b3; fa-cubes</option>
            <option value="fa fa-cut icon icon-size">&#xf0c4; fa-cut</option>
            <option value="fa fa-cutlery icon icon-size">&#xf0f5; fa-cutlery</option>
            <option value="fa fa-dashboard icon icon-size">&#xf0e4; fa-dashboard</option>
            <option value="fa fa-dashcube icon icon-size">&#xf210; fa-dashcube</option>
            <option value="fa fa-database icon icon-size">&#xf1c0; fa-database</option>
            <option value="fa fa-dedent icon icon-size">&#xf03b; fa-dedent</option>
            <option value="fa fa-delicious icon icon-size">&#xf1a5; fa-delicious</option>
            <option value="fa fa-desktop icon icon-size">&#xf108; fa-desktop</option>
            <option value="fa fa-deviantart icon icon-size">&#xf1bd; fa-deviantart</option>
            <option value="fa fa-diamond icon icon-size">&#xf219; fa-diamond</option>
            <option value="fa fa-digg icon icon-size">&#xf1a6; fa-digg</option>
            <option value="fa fa-dollar icon icon-size">&#xf155; fa-dollar</option>
            <option value="fa fa-download icon icon-size">&#xf019; fa-download</option>
            <option value="fa fa-dribbble icon icon-size">&#xf17d; fa-dribbble</option>
            <option value="fa fa-dropbox icon icon-size">&#xf16b; fa-dropbox</option>
            <option value="fa fa-drupal icon icon-size">&#xf1a9; fa-drupal</option>
            <option value="fa fa-edit icon icon-size">&#xf044; fa-edit</option>
            <option value="fa fa-eject icon icon-size">&#xf052; fa-eject</option>
            <option value="fa fa-ellipsis-h icon icon-size">&#xf141; fa-ellipsis-h</option>
            <option value="fa fa-ellipsis-v icon icon-size">&#xf142; fa-ellipsis-v</option>
            <option value="fa fa-empire icon icon-size">&#xf1d1; fa-empire</option>
            <option value="fa fa-envelope icon icon-size">&#xf0e0; fa-envelope</option>
            <option value="fa fa-envelope-o icon icon-size">&#xf003; fa-envelope-o</option>
            <option value="fa fa-eur icon icon-size">&#xf153; fa-eur</option>
            <option value="fa fa-euro icon icon-size">&#xf153; fa-euro</option>
            <option value="fa fa-exchange icon icon-size">&#xf0ec; fa-exchange</option>
            <option value="fa fa-exclamation icon icon-size">&#xf12a; fa-exclamation</option>
            <option value="fa fa-exclamation-circle icon icon-size">&#xf06a; fa-exclamation-circle</option>
            <option value="fa fa-exclamation-triangle icon icon-size">&#xf071; fa-exclamation-triangle</option>
            <option value="fa fa-expand icon icon-size">&#xf065; fa-expand</option>
            <option value="fa fa-expeditedssl icon icon-size">&#xf23e; fa-expeditedssl</option>
            <option value="fa fa-external-link icon icon-size">&#xf08e; fa-external-link</option>
            <option value="fa fa-external-link-square icon icon-size">&#xf14c; fa-external-link-square</option>
            <option value="fa fa-eye icon icon-size">&#xf06e; fa-eye</option>
            <option value="fa fa-eye-slash icon icon-size">&#xf070; fa-eye-slash</option>
            <option value="fa fa-eyedropper icon icon-size">&#xf1fb; fa-eyedropper</option>
            <option value="fa fa-facebook icon icon-size">&#xf09a; fa-facebook</option>
            <option value="fa fa-facebook-f icon icon-size">&#xf09a; fa-facebook-f</option>
            <option value="fa fa-facebook-official icon icon-size">&#xf230; fa-facebook-official</option>
            <option value="fa fa-facebook-square icon icon-size">&#xf082; fa-facebook-square</option>
            <option value="fa fa-fast-backward icon icon-size">&#xf049; fa-fast-backward</option>
            <option value="fa fa-fast-forward icon icon-size">&#xf050; fa-fast-forward</option>
            <option value="fa fa-fax icon icon-size">&#xf1ac; fa-fax</option>
            <option value="fa fa-feed icon icon-size">&#xf09e; fa-feed</option>
            <option value="fa fa-female icon icon-size">&#xf182; fa-female</option>
            <option value="fa fa-fighter-jet icon icon-size">&#xf0fb; fa-fighter-jet</option>
            <option value="fa fa-file icon icon-size">&#xf15b; fa-file</option>
            <option value="fa fa-file-archive-o icon icon-size">&#xf1c6; fa-file-archive-o</option>
            <option value="fa fa-file-audio-o icon icon-size">&#xf1c7; fa-file-audio-o</option>
            <option value="fa fa-file-code-o icon icon-size">&#xf1c9; fa-file-code-o</option>
            <option value="fa fa-file-excel-o icon icon-size">&#xf1c3; fa-file-excel-o</option>
            <option value="fa fa-file-image-o icon icon-size">&#xf1c5; fa-file-image-o</option>
            <option value="fa fa-file-movie-o icon icon-size">&#xf1c8; fa-file-movie-o</option>
            <option value="fa fa-file-o icon icon-size">&#xf016; fa-file-o</option>
            <option value="fa fa-file-pdf-o icon icon-size">&#xf1c1; fa-file-pdf-o</option>
            <option value="fa fa-file-photo-o icon icon-size">&#xf1c5; fa-file-photo-o</option>
            <option value="fa fa-file-picture-o icon icon-size">&#xf1c5; fa-file-picture-o</option>
            <option value="fa fa-file-powerpoint-o icon icon-size">&#xf1c4; fa-file-powerpoint-o</option>
            <option value="fa fa-file-sound-o icon icon-size">&#xf1c7; fa-file-sound-o</option>
            <option value="fa fa-file-text icon icon-size">&#xf15c; fa-file-text</option>
            <option value="fa fa-file-text-o icon icon-size">&#xf0f6; fa-file-text-o</option>
            <option value="fa fa-file-video-o icon icon-size">&#xf1c8; fa-file-video-o</option>
            <option value="fa fa-file-word-o icon icon-size">&#xf1c2; fa-file-word-o</option>
            <option value="fa fa-file-zip-o icon icon-size">&#xf1c6; fa-file-zip-o</option>
            <option value="fa fa-files-o icon icon-size">&#xf0c5; fa-files-o</option>
            <option value="fa fa-film icon icon-size">&#xf008; fa-film</option>
            <option value="fa fa-filter icon icon-size">&#xf0b0; fa-filter</option>
            <option value="fa fa-fire icon icon-size">&#xf06d; fa-fire</option>
            <option value="fa fa-fire-extinguisher icon icon-size">&#xf134; fa-fire-extinguisher</option>
            <option value="fa fa-firefox icon icon-size">&#xf269; fa-firefox</option>
            <option value="fa fa-flag icon icon-size">&#xf024; fa-flag</option>
            <option value="fa fa-flag-checkered icon icon-size">&#xf11e; fa-flag-checkered</option>
            <option value="fa fa-flag-o icon icon-size">&#xf11d; fa-flag-o</option>
            <option value="fa fa-flash icon icon-size">&#xf0e7; fa-flash</option>
            <option value="fa fa-flask icon icon-size">&#xf0c3; fa-flask</option>
            <option value="fa fa-flickr icon icon-size">&#xf16e; fa-flickr</option>
            <option value="fa fa-floppy-o icon icon-size">&#xf0c7; fa-floppy-o</option>
            <option value="fa fa-folder icon icon-size">&#xf07b; fa-folder</option>
            <option value="fa fa-folder-o icon icon-size">&#xf114; fa-folder-o</option>
            <option value="fa fa-folder-open icon icon-size">&#xf07c; fa-folder-open</option>
            <option value="fa fa-folder-open-o icon icon-size">&#xf115; fa-folder-open-o</option>
            <option value="fa fa-font icon icon-size">&#xf031; fa-font</option>
            <option value="fa fa-fonticons icon icon-size">&#xf280; fa-fonticons</option>
            <option value="fa fa-forumbee icon icon-size">&#xf211; fa-forumbee</option>
            <option value="fa fa-forward icon icon-size">&#xf04e; fa-forward</option>
            <option value="fa fa-foursquare icon icon-size">&#xf180; fa-foursquare</option>
            <option value="fa fa-frown-o icon icon-size">&#xf119; fa-frown-o</option>
            <option value="fa fa-futbol-o icon icon-size">&#xf1e3; fa-futbol-o</option>
            <option value="fa fa-gamepad icon icon-size">&#xf11b; fa-gamepad</option>
            <option value="fa fa-gavel icon icon-size">&#xf0e3; fa-gavel</option>
            <option value="fa fa-gbp icon icon-size">&#xf154; fa-gbp</option>
            <option value="fa fa-ge icon icon-size">&#xf1d1; fa-ge</option>
            <option value="fa fa-gear icon icon-size">&#xf013; fa-gear</option>
            <option value="fa fa-gears icon icon-size">&#xf085; fa-gears</option>
            <option value="fa fa-genderless icon icon-size">&#xf22d; fa-genderless</option>
            <option value="fa fa-get-pocket icon icon-size">&#xf265; fa-get-pocket</option>
            <option value="fa fa-gg icon icon-size">&#xf260; fa-gg</option>
            <option value="fa fa-gg-circle icon icon-size">&#xf261; fa-gg-circle</option>
            <option value="fa fa-gift icon icon-size">&#xf06b; fa-gift</option>
            <option value="fa fa-git icon icon-size">&#xf1d3; fa-git</option>
            <option value="fa fa-git-square icon icon-size">&#xf1d2; fa-git-square</option>
            <option value="fa fa-github icon icon-size">&#xf09b; fa-github</option>
            <option value="fa fa-github-alt icon icon-size">&#xf113; fa-github-alt</option>
            <option value="fa fa-github-square icon icon-size">&#xf092; fa-github-square</option>
            <option value="fa fa-gittip icon icon-size">&#xf184; fa-gittip</option>
            <option value="fa fa-glass icon icon-size">&#xf000; fa-glass</option>
            <option value="fa fa-globe icon icon-size">&#xf0ac; fa-globe</option>
            <option value="fa fa-google icon icon-size">&#xf1a0; fa-google</option>
            <option value="fa fa-google-plus icon icon-size">&#xf0d5; fa-google-plus</option>
            <option value="fa fa-google-plus-square icon icon-size">&#xf0d4; fa-google-plus-square</option>
            <option value="fa fa-google-wallet icon icon-size">&#xf1ee; fa-google-wallet</option>
            <option value="fa fa-graduation-cap icon icon-size">&#xf19d; fa-graduation-cap</option>
            <option value="fa fa-gratipay icon icon-size">&#xf184; fa-gratipay</option>
            <option value="fa fa-group icon icon-size">&#xf0c0; fa-group</option>
            <option value="fa fa-h-square icon icon-size">&#xf0fd; fa-h-square</option>
            <option value="fa fa-hacker-news icon icon-size">&#xf1d4; fa-hacker-news</option>
            <option value="fa fa-hand-grab-o icon icon-size">&#xf255; fa-hand-grab-o</option>
            <option value="fa fa-hand-lizard-o icon icon-size">&#xf258; fa-hand-lizard-o</option>
            <option value="fa fa-hand-o-down icon icon-size">&#xf0a7; fa-hand-o-down</option>
            <option value="fa fa-hand-o-left icon icon-size">&#xf0a5; fa-hand-o-left</option>
            <option value="fa fa-hand-o-right icon icon-size">&#xf0a4; fa-hand-o-right</option>
            <option value="fa fa-hand-o-up icon icon-size">&#xf0a6; fa-hand-o-up</option>
            <option value="fa fa-hand-paper-o icon icon-size">&#xf256; fa-hand-paper-o</option>
            <option value="fa fa-hand-peace-o icon icon-size">&#xf25b; fa-hand-peace-o</option>
            <option value="fa fa-hand-pointer-o icon icon-size">&#xf25a; fa-hand-pointer-o</option>
            <option value="fa fa-hand-rock-o icon icon-size">&#xf255; fa-hand-rock-o</option>
            <option value="fa fa-hand-scissors-o icon icon-size">&#xf257; fa-hand-scissors-o</option>
            <option value="fa fa-hand-spock-o icon icon-size">&#xf259; fa-hand-spock-o</option>
            <option value="fa fa-hand-stop-o icon icon-size">&#xf256; fa-hand-stop-o</option>
            <option value="fa fa-hdd-o icon icon-size">&#xf0a0; fa-hdd-o</option>
            <option value="fa fa-header icon icon-size">&#xf1dc; fa-header</option>
            <option value="fa fa-headphones icon icon-size">&#xf025; fa-headphones</option>
            <option value="fa fa-heart icon icon-size">&#xf004; fa-heart</option>
            <option value="fa fa-heart-o icon icon-size">&#xf08a; fa-heart-o</option>
            <option value="fa fa-heartbeat icon icon-size">&#xf21e; fa-heartbeat</option>
            <option value="fa fa-history icon icon-size">&#xf1da; fa-history</option>
            <option value="fa fa-home icon icon-size">&#xf015; fa-home</option>
            <option value="fa fa-hospital-o icon icon-size">&#xf0f8; fa-hospital-o</option>
            <option value="fa fa-hotel icon icon-size">&#xf236; fa-hotel</option>
            <option value="fa fa-hourglass icon icon-size">&#xf254; fa-hourglass</option>
            <option value="fa fa-hourglass-1 icon icon-size">&#xf251; fa-hourglass-1</option>
            <option value="fa fa-hourglass-2 icon icon-size">&#xf252; fa-hourglass-2</option>
            <option value="fa fa-hourglass-3 icon icon-size">&#xf253; fa-hourglass-3</option>
            <option value="fa fa-hourglass-end icon icon-size">&#xf253; fa-hourglass-end</option>
            <option value="fa fa-hourglass-half icon icon-size">&#xf252; fa-hourglass-half</option>
            <option value="fa fa-hourglass-o icon icon-size">&#xf250; fa-hourglass-o</option>
            <option value="fa fa-hourglass-start icon icon-size">&#xf251; fa-hourglass-start</option>
            <option value="fa fa-houzz icon icon-size">&#xf27c; fa-houzz</option>
            <option value="fa fa-html5 icon icon-size">&#xf13b; fa-html5</option>
            <option value="fa fa-i-cursor icon icon-size">&#xf246; fa-i-cursor</option>
            <option value="fa fa-ils icon icon-size">&#xf20b; fa-ils</option>
            <option value="fa fa-image icon icon-size">&#xf03e; fa-image</option>
            <option value="fa fa-inbox icon icon-size">&#xf01c; fa-inbox</option>
            <option value="fa fa-indent icon icon-size">&#xf03c; fa-indent</option>
            <option value="fa fa-industry icon icon-size">&#xf275; fa-industry</option>
            <option value="fa fa-info icon icon-size">&#xf129; fa-info</option>
            <option value="fa fa-info-circle icon icon-size">&#xf05a; fa-info-circle</option>
            <option value="fa fa-inr icon icon-size">&#xf156; fa-inr</option>
            <option value="fa fa-instagram icon icon-size">&#xf16d; fa-instagram</option>
            <option value="fa fa-institution icon icon-size">&#xf19c; fa-institution</option>
            <option value="fa fa-internet-explorer icon icon-size">&#xf26b; fa-internet-explorer</option>
            <option value="fa fa-intersex icon icon-size">&#xf224; fa-intersex</option>
            <option value="fa fa-ioxhost icon icon-size">&#xf208; fa-ioxhost</option>
            <option value="fa fa-italic icon icon-size">&#xf033; fa-italic</option>
            <option value="fa fa-joomla icon icon-size">&#xf1aa; fa-joomla</option>
            <option value="fa fa-jpy icon icon-size">&#xf157; fa-jpy</option>
            <option value="fa fa-jsfiddle icon icon-size">&#xf1cc; fa-jsfiddle</option>
            <option value="fa fa-key icon icon-size">&#xf084; fa-key</option>
            <option value="fa fa-keyboard-o icon icon-size">&#xf11c; fa-keyboard-o</option>
            <option value="fa fa-krw icon icon-size">&#xf159; fa-krw</option>
            <option value="fa fa-language icon icon-size">&#xf1ab; fa-language</option>
            <option value="fa fa-laptop icon icon-size">&#xf109; fa-laptop</option>
            <option value="fa fa-lastfm icon icon-size">&#xf202; fa-lastfm</option>
            <option value="fa fa-lastfm-square icon icon-size">&#xf203; fa-lastfm-square</option>
            <option value="fa fa-leaf icon icon-size">&#xf06c; fa-leaf</option>
            <option value="fa fa-leanpub icon icon-size">&#xf212; fa-leanpub</option>
            <option value="fa fa-legal icon icon-size">&#xf0e3; fa-legal</option>
            <option value="fa fa-lemon-o icon icon-size">&#xf094; fa-lemon-o</option>
            <option value="fa fa-level-down icon icon-size">&#xf149; fa-level-down</option>
            <option value="fa fa-level-up icon icon-size">&#xf148; fa-level-up</option>
            <option value="fa fa-life-bouy icon icon-size">&#xf1cd; fa-life-bouy</option>
            <option value="fa fa-life-buoy icon icon-size">&#xf1cd; fa-life-buoy</option>
            <option value="fa fa-life-ring icon icon-size">&#xf1cd; fa-life-ring</option>
            <option value="fa fa-life-saver icon icon-size">&#xf1cd; fa-life-saver</option>
            <option value="fa fa-lightbulb-o icon icon-size">&#xf0eb; fa-lightbulb-o</option>
            <option value="fa fa-line-chart icon icon-size">&#xf201; fa-line-chart</option>
            <option value="fa fa-link icon icon-size">&#xf0c1; fa-link</option>
            <option value="fa fa-linkedin icon icon-size">&#xf0e1; fa-linkedin</option>
            <option value="fa fa-linkedin-square icon icon-size">&#xf08c; fa-linkedin-square</option>
            <option value="fa fa-linux icon icon-size">&#xf17c; fa-linux</option>
            <option value="fa fa-list icon icon-size">&#xf03a; fa-list</option>
            <option value="fa fa-list-alt icon icon-size">&#xf022; fa-list-alt</option>
            <option value="fa fa-list-ol icon icon-size">&#xf0cb; fa-list-ol</option>
            <option value="fa fa-list-ul icon icon-size">&#xf0ca; fa-list-ul</option>
            <option value="fa fa-location-arrow icon icon-size">&#xf124; fa-location-arrow</option>
            <option value="fa fa-lock icon icon-size">&#xf023; fa-lock</option>
            <option value="fa fa-long-arrow-down icon icon-size">&#xf175; fa-long-arrow-down</option>
            <option value="fa fa-long-arrow-left icon icon-size">&#xf177; fa-long-arrow-left</option>
            <option value="fa fa-long-arrow-right icon icon-size">&#xf178; fa-long-arrow-right</option>
            <option value="fa fa-long-arrow-up icon icon-size">&#xf176; fa-long-arrow-up</option>
            <option value="fa fa-magic icon icon-size">&#xf0d0; fa-magic</option>
            <option value="fa fa-magnet icon icon-size">&#xf076; fa-magnet</option>
            <option value="fa fa-mars-stroke-v icon icon-size">&#xf22a; fa-mars-stroke-v</option>
            <option value="fa fa-maxcdn icon icon-size">&#xf136; fa-maxcdn</option>
            <option value="fa fa-meanpath icon icon-size">&#xf20c; fa-meanpath</option>
            <option value="fa fa-medium icon icon-size">&#xf23a; fa-medium</option>
            <option value="fa fa-medkit icon icon-size">&#xf0fa; fa-medkit</option>
            <option value="fa fa-meh-o icon icon-size">&#xf11a; fa-meh-o</option>
            <option value="fa fa-mercury icon icon-size">&#xf223; fa-mercury</option>
            <option value="fa fa-microphone icon icon-size">&#xf130; fa-microphone</option>
            <option value="fa fa-mobile icon icon-size">&#xf10b; fa-mobile</option>
            <option value="fa fa-motorcycle icon icon-size">&#xf21c; fa-motorcycle</option>
            <option value="fa fa-mouse-pointer icon icon-size">&#xf245; fa-mouse-pointer</option>
            <option value="fa fa-music icon icon-size">&#xf001; fa-music</option>
            <option value="fa fa-navicon icon icon-size">&#xf0c9; fa-navicon</option>
            <option value="fa fa-neuter icon icon-size">&#xf22c; fa-neuter</option>
            <option value="fa fa-newspaper-o icon icon-size">&#xf1ea; fa-newspaper-o</option>
            <option value="fa fa-opencart icon icon-size">&#xf23d; fa-opencart</option>
            <option value="fa fa-openid icon icon-size">&#xf19b; fa-openid</option>
            <option value="fa fa-opera icon icon-size">&#xf26a; fa-opera</option>
            <option value="fa fa-outdent icon icon-size">&#xf03b; fa-outdent</option>
            <option value="fa fa-pagelines icon icon-size">&#xf18c; fa-pagelines</option>
            <option value="fa fa-paper-plane-o icon icon-size">&#xf1d9; fa-paper-plane-o</option>
            <option value="fa fa-paperclip icon icon-size">&#xf0c6; fa-paperclip</option>
            <option value="fa fa-paragraph icon icon-size">&#xf1dd; fa-paragraph</option>
            <option value="fa fa-paste icon icon-size">&#xf0ea; fa-paste</option>
            <option value="fa fa-pause icon icon-size">&#xf04c; fa-pause</option>
            <option value="fa fa-paw icon icon-size">&#xf1b0; fa-paw</option>
            <option value="fa fa-paypal icon icon-size">&#xf1ed; fa-paypal</option>
            <option value="fa fa-pencil icon icon-size">&#xf040; fa-pencil</option>
            <option value="fa fa-pencil-square-o icon icon-size">&#xf044; fa-pencil-square-o</option>
            <option value="fa fa-phone icon icon-size">&#xf095; fa-phone</option>
            <option value="fa fa-photo icon icon-size">&#xf03e; fa-photo</option>
            <option value="fa fa-picture-o icon icon-size">&#xf03e; fa-picture-o</option>
            <option value="fa fa-pie-chart icon icon-size">&#xf200; fa-pie-chart</option>
            <option value="fa fa-pied-piper icon icon-size">&#xf1a7; fa-pied-piper</option>
            <option value="fa fa-pied-piper-alt icon icon-size">&#xf1a8; fa-pied-piper-alt</option>
            <option value="fa fa-pinterest icon icon-size">&#xf0d2; fa-pinterest</option>
            <option value="fa fa-pinterest-p icon icon-size">&#xf231; fa-pinterest-p</option>
            <option value="fa fa-pinterest-square icon icon-size">&#xf0d3; fa-pinterest-square</option>
            <option value="fa fa-plane icon icon-size">&#xf072; fa-plane</option>
            <option value="fa fa-play icon icon-size">&#xf04b; fa-play</option>
            <option value="fa fa-play-circle icon icon-size">&#xf144; fa-play-circle</option>
            <option value="fa fa-play-circle-o icon icon-size">&#xf01d; fa-play-circle-o</option>
            <option value="fa fa-plug icon icon-size">&#xf1e6; fa-plug</option>
            <option value="fa fa-plus icon icon-size">&#xf067; fa-plus</option>
            <option value="fa fa-plus-circle icon icon-size">&#xf055; fa-plus-circle</option>
            <option value="fa fa-plus-square icon icon-size">&#xf0fe; fa-plus-square</option>
            <option value="fa fa-plus-square-o icon icon-size">&#xf196; fa-plus-square-o</option>
            <option value="fa fa-power-off icon icon-size">&#xf011; fa-power-off</option>
            <option value="fa fa-print icon icon-size">&#xf02f; fa-print</option>
            <option value="fa fa-puzzle-piece icon icon-size">&#xf12e; fa-puzzle-piece</option>
            <option value="fa fa-qq icon icon-size">&#xf1d6; fa-qq</option>
            <option value="fa fa-qrcode icon icon-size">&#xf029; fa-qrcode</option>
            <option value="fa fa-question icon icon-size">&#xf128; fa-question</option>
            <option value="fa fa-question-circle icon icon-size">&#xf059; fa-question-circle</option>
            <option value="fa fa-quote-left icon icon-size">&#xf10d; fa-quote-left</option>
            <option value="fa fa-quote-right icon icon-size">&#xf10e; fa-quote-right</option>
            <option value="fa fa-ra icon icon-size">&#xf1d0; fa-ra</option>
            <option value="fa fa-random icon icon-size">&#xf074; fa-random</option>
            <option value="fa fa-rebel icon icon-size">&#xf1d0; fa-rebel</option>
            <option value="fa fa-recycle icon icon-size">&#xf1b8; fa-recycle</option>
            <option value="fa fa-reddit icon icon-size">&#xf1a1; fa-reddit</option>
            <option value="fa fa-reddit-square icon icon-size">&#xf1a2; fa-reddit-square</option>
            <option value="fa fa-refresh icon icon-size">&#xf021; fa-refresh</option>
            <option value="fa fa-registered icon icon-size">&#xf25d; fa-registered</option>
            <option value="fa fa-remove icon icon-size">&#xf00d; fa-remove</option>
            <option value="fa fa-renren icon icon-size">&#xf18b; fa-renren</option>
            <option value="fa fa-reorder icon icon-size">&#xf0c9; fa-reorder</option>
            <option value="fa fa-repeat icon icon-size">&#xf01e; fa-repeat</option>
            <option value="fa fa-reply icon icon-size">&#xf112; fa-reply</option>
            <option value="fa fa-reply-all icon icon-size">&#xf122; fa-reply-all</option>
            <option value="fa fa-retweet icon icon-size">&#xf079; fa-retweet</option>
            <option value="fa fa-rmb icon icon-size">&#xf157; fa-rmb</option>
            <option value="fa fa-road icon icon-size">&#xf018; fa-road</option>
            <option value="fa fa-rocket icon icon-size">&#xf135; fa-rocket</option>
            <option value="fa fa-rotate-left icon icon-size">&#xf0e2; fa-rotate-left</option>
            <option value="fa fa-rotate-right icon icon-size">&#xf01e; fa-rotate-right</option>
            <option value="fa fa-rouble icon icon-size">&#xf158; fa-rouble</option>
            <option value="fa fa-rss icon icon-size">&#xf09e; fa-rss</option>
            <option value="fa fa-rss-square icon icon-size">&#xf143; fa-rss-square</option>
            <option value="fa fa-rub icon icon-size">&#xf158; fa-rub</option>
            <option value="fa fa-ruble icon icon-size">&#xf158; fa-ruble</option>
            <option value="fa fa-rupee icon icon-size">&#xf156; fa-rupee</option>
            <option value="fa fa-safari icon icon-size">&#xf267; fa-safari</option>
            <option value="fa fa-sliders icon icon-size">&#xf1de; fa-sliders</option>
            <option value="fa fa-slideshare icon icon-size">&#xf1e7; fa-slideshare</option>
            <option value="fa fa-smile-o icon icon-size">&#xf118; fa-smile-o</option>
            <option value="fa fa-sort-asc icon icon-size">&#xf0de; fa-sort-asc</option>
            <option value="fa fa-sort-desc icon icon-size">&#xf0dd; fa-sort-desc</option>
            <option value="fa fa-sort-down icon icon-size">&#xf0dd; fa-sort-down</option>
            <option value="fa fa-spinner icon icon-size">&#xf110; fa-spinner</option>
            <option value="fa fa-spoon icon icon-size">&#xf1b1; fa-spoon</option>
            <option value="fa fa-spotify icon icon-size">&#xf1bc; fa-spotify</option>
            <option value="fa fa-square icon icon-size">&#xf0c8; fa-square</option>
            <option value="fa fa-square-o icon icon-size">&#xf096; fa-square-o</option>
            <option value="fa fa-star icon icon-size">&#xf005; fa-star</option>
            <option value="fa fa-star-half icon icon-size">&#xf089; fa-star-half</option>
            <option value="fa fa-stop icon icon-size">&#xf04d; fa-stop</option>
            <option value="fa fa-subscript icon icon-size">&#xf12c; fa-subscript</option>
            <option value="fa fa-tablet icon icon-size">&#xf10a; fa-tablet</option>
            <option value="fa fa-tachometer icon icon-size">&#xf0e4; fa-tachometer</option>
            <option value="fa fa-tag icon icon-size">&#xf02b; fa-tag</option>
            <option value="fa fa-tags icon icon-size">&#xf02c; fa-tags</option>
        </select>

        <!-- <input class="form-control" name="icon" type="text" id="icon" value="{{ $propertytype->icon??''}}" > -->
        {!! $errors->first('icon', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="form-group {{ $errors->has('status') ? 'has-error' : ''}}">
    <label for="status" class="col-md-4 control-label">{{ 'Status' }}</label>
    <div class="col-md-6">
        @include('includes.status_select_html',['variable'=>$time->status??''])
        {!! $errors->first('status', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group">
    <div class="col-md-offset-4 col-md-4">
        <input class="btn btn-primary" type="submit" value="{{ $submitButtonText??'Create' }}">
    </div>
</div>
@push('js')
<script>CKEDITOR.replace( 'description' );</script>
@endpush